### ISSUE TITLE
支持 Perplexity AI？

### ISSUE THREAD

**Issue by bentwnghk** [MartialBE/one-api#232]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
是否不支持 Perplexity AI？
**复现步骤**
如下圖添加自定義渠道，測試錯誤返回： Provider API error: bad response status code 404.
**预期结果**

**相关截图**
![螢幕擷取畫面 2024-05-27 111037](https://github.com/MartialBE/one-api/assets/101241940/6450c355-4997-4648-8437-becd16120e32)

**Comment by MartialBE** [comment]
看了他的api，区别是没有携带/v1。 
目前请求时都会携带这个api的版本号
我晚点看看怎么处理比较好。

**Comment by bentwnghk** [comment]
辛苦了，先謝謝你！

**Comment by MartialBE** [comment]
晚点试试dev版本镜像。 在 自定义渠道 中 api版本中 填入disable 试试

<img width="871" alt="image" src="https://github.com/MartialBE/one-api/assets/42402987/c9fd6e90-b304-443e-8545-388fe0fb3286">

**Comment by bentwnghk** [comment]
使用dev版本镜像，容器啟動錯誤：
![image](https://github.com/MartialBE/one-api/assets/101241940/cb01b0f2-5eeb-43a9-a7c1-f51e12b6a7dc)

**Comment by MartialBE** [comment]
你在启动时 设置了 --config= 参数了吗

**Comment by MartialBE** [comment]
因为之前没有判断 用户传入的 配置文件地址 是否正确，这次加上判断了。你可能需要检查 --config 设置的文件地址是否存在， 在容器中 是容器的文件地址，而不是你宿主机的 文件地址

**Comment by bentwnghk** [comment]
```
version: '3.4'

services:
  one-api:
    image: martialbe/one-api:dev
    container_name: one-api
    restart: always
    # privileged: true
    command: --log-dir /app/logs
    ports:
      - "3099:3000"
    volumes:
      - /root/oneapi:/data
      - /root/oneapi/logs:/app/logs
    environment:
      - SQL_DSN=oneapi:xxx@tcp(db:3306)/one-api  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=xxx # 修改为随机字符串
      - TZ=Asia/Hong_Kong
      - STORAGE_SMMS_SECRET=xxx  # 设置之后将使用 sm.ms 作为图片存储服务
      - STORAGE_IMGUR_CLIENT_ID=xxx  # 设置之后将使用 imgur 作为图片存储服务
      # - GEMINI_VERSION=v1beta
    depends_on:
      - redis
      - db
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3099/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: oneapi-redis
    restart: always

  db:
    image: mysql:8.2.0
    restart: always
    container_name: oneapi-mysql
    volumes:
      - /root/oneapi/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    ports:
      - '3307:3306'
    environment:
      TZ: Asia/Hong_Kong   # 设置时区
      MYSQL_ROOT_PASSWORD: 'xxx' # 设置 root 用户的密码
      MYSQL_USER: oneapi   # 创建专用用户
      MYSQL_PASSWORD: 'xxx'    # 设置专用用户密码
      MYSQL_DATABASE: one-api   # 自动创建数据库
```
