### ISSUE TITLE
A small help needed

### ISSUE THREAD

**Issue by Urmi10799** [MartialBE/one-api#66]
I wonder how to change the default font family. For example, I want to use `Söhne, Helvetica, sans-serif` as the new default font. Can you guide me on how to modify it?

**Comment by MartialBE** [comment]
Here's how you can change the default font family to Söhne, Helvetica, sans-serif:

1. Create a `fonts` directory inside `web/src/assets` and place your font files in it.
2. In your `web/src/scss/style.scss` file, add the following code:

```scss
@font-face {
  font-family: 'Your Font Name';
  src: local('Your Font Name'), url('../fonts/YourFontName.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
}
```

Replace `'Your Font Name'` and `'YourFontName.woff2'` with the actual name of your font.

3. Modify the `fontFamily` in `web/src/config.js` to `YourFontName, Helvetica, sans-serif`.

Please ensure that the path to the font file is correct and that the browser supports the font file format. In the above example, we assume that the font file is in woff2 format, which is widely supported by modern browsers.
